Part 1: Dataset Creation

In [1]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

In [2]:
'''

Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array

'''

num_dimensions = sales_data.ndim
print("Number of dimension in sales_data: ",num_dimensions)

shape = sales_data.shape
print("Shape of sales_data: ",shape)

total_values = sales_data.size
print("Total number of values: ",total_values)

data_type = sales_data.dtype
print("Data type of the array: ",data_type)

memory_occupied = sales_data.nbytes
print("Memory occupied by the array: ",memory_occupied," bytes")

Number of dimension in sales_data:  2
Shape of sales_data:  (5, 6)
Total number of values:  30
Data type of the array:  int64
Memory occupied by the array:  240  bytes


In [3]:
'''

Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations

'''

total_stores = stores.size
print("Total number of stores: ", total_stores)

total_categories = categories.size
print("Total number of product categories: ", total_categories)

total_combinations = total_stores * total_categories
print("Total number of store-category combinations: ", total_combinations)

Total number of stores:  5
Total number of product categories:  6
Total number of store-category combinations:  30


In [4]:
'''

Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.14

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.

'''

sales_data_float32 = sales_data.astype(np.float32)
sales_data_float64 = sales_data.astype(np.float64)

print("Memory used by sales_data_float32:", sales_data_float32.nbytes, "bytes")
print("Memory used by sales_data_float64:", sales_data_float64.nbytes, "bytes")

print("Memory usage difference:", sales_data_float64.nbytes - sales_data_float32.nbytes, "bytes")


Memory used by sales_data_float32: 120 bytes
Memory used by sales_data_float64: 240 bytes
Memory usage difference: 120 bytes


Part 3: Indexing and Data Extraction

In [5]:
'''

Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

'''

banglore_sales = sales_data[0]
print("Sales data for Bengaluru store:", banglore_sales)

Sales data for Bengaluru store: [850000 420000 310000 275000 190000 225000]


In [6]:
'''

Question 5: Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories.

'''

mumbai_cost = sales_data[1, 3]
print("Total cost incurred by the Mumbai store:", mumbai_cost)

Total cost incurred by the Mumbai store: 310000


In [7]:
'''

Question 6: Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

'''
electronics_sales = sales_data[:, 2]
print("Electronics sales across all stores:", electronics_sales)

Electronics sales across all stores: [310000 295000 340000 375000 280000]


In [8]:
'''

Question 7: Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.

'''

clothing_cost = cost_data[:, 1]
print("Clothing cost across all stores:", clothing_cost)

Clothing cost across all stores: [315000 350000 295000 390000 310000]


In [9]:
'''

Question 8: Hyderabad Furniture Performance
Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit

'''

furniture_sales_hyderabad = sales_data[1, 3]
furniture_cost_hyderabad = cost_data[1, 3]
furniture_profit_hyderabad = furniture_sales_hyderabad - furniture_cost_hyderabad
print("Furniture sales in Hyderabad:", furniture_sales_hyderabad)
print("Furniture cost in Hyderabad:", furniture_cost_hyderabad)
print("Furniture profit in Hyderabad:", furniture_profit_hyderabad)

Furniture sales in Hyderabad: 310000
Furniture cost in Hyderabad: 225000
Furniture profit in Hyderabad: 85000


In [10]:
'''
Question 9: Chennai Category Range
Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture

Use array slicing.

'''

chennai_sales = sales_data[2, 1:4]
print("Chennai's sales for Groceries, Clothing, and Furniture:", chennai_sales)

Chennai's sales for Groceries, Clothing, and Furniture: [390000 340000 260000]


In [11]:
'''

Question 10: Selected Store Analysis

Extract sales data for:
Bengaluru
Chennai
Pune

Include only:
Electronics
Clothing
Beauty

Use advanced indexing.

'''

sales_data_bengaluru_chennai_pune = sales_data[[0, 2, 4], [0, 2, 4]]
print("Sales data for Bengaluru, Chennai, and Pune (Electronics, Clothing, Beauty):", sales_data_bengaluru_chennai_pune)

Sales data for Bengaluru, Chennai, and Pune (Electronics, Clothing, Beauty): [850000 340000 175000]


Part 4: Sales Aggregation

In [12]:
'''

Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.

'''

total_sales_revenue = np.sum(sales_data)
print("Total sales revenue generated by all stores and all categories:", total_sales_revenue)

Total sales revenue generated by all stores and all categories: 11675000


In [13]:
'''

Question 12: Store-Wise Sales
Calculate total sales revenue for each store.

Display the result together with the store names.

'''

total_sales_per_store = np.sum(sales_data, axis=1)
for store, total_sales in zip(stores, total_sales_per_store):
    print(f"Total sales revenue for {store}: {total_sales}")

Total sales revenue for Bengaluru: 2270000
Total sales revenue for Hyderabad: 2295000
Total sales revenue for Chennai: 2310000
Total sales revenue for Mumbai: 2820000
Total sales revenue for Pune: 1980000


In [14]:
'''

Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales.

'''

total_sales_per_category = np.sum(sales_data, axis=0)
for category, total_sales in zip(categories, total_sales_per_category):
    print(f"Total sales for {category}: {total_sales}")

Total sales for Electronics: 4290000
Total sales for Groceries: 2185000
Total sales for Clothing: 1600000
Total sales for Furniture: 1415000
Total sales for Beauty: 1010000
Total sales for Sports: 1175000


In [15]:
'''

Question 14: Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.

'''

average_sales_per_store = np.mean(sales_data, axis=1)
for store, average_sales in zip(stores, average_sales_per_store):
    print(f"Average sales for {store}: {average_sales}")

Average sales for Bengaluru: 378333.3333333333
Average sales for Hyderabad: 382500.0
Average sales for Chennai: 385000.0
Average sales for Mumbai: 470000.0
Average sales for Pune: 330000.0


In [16]:
'''

Question 15: Average Sales Per Category
Calculate the average sales of each product category across the five stores.

'''
average_sales_per_category = np.mean(sales_data, axis=0)
for category, average_sales in zip(categories, average_sales_per_category):
    print(f"Average sales for {category}: {average_sales}")

Average sales for Electronics: 858000.0
Average sales for Groceries: 437000.0
Average sales for Clothing: 320000.0
Average sales for Furniture: 283000.0
Average sales for Beauty: 202000.0
Average sales for Sports: 235000.0


In [17]:
'''

Question 16: Highest-Selling Store
Identify:

Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().

'''

highest_selling_store_index = np.argmax(total_sales_per_store)
highest_selling_store_name = stores[highest_selling_store_index]
highest_selling_store_sales = total_sales_per_store[highest_selling_store_index]
print(f"Store with highest sales: {highest_selling_store_name}")
print(f"Total sales for {highest_selling_store_name}: {highest_selling_store_sales}")

Store with highest sales: Mumbai
Total sales for Mumbai: 2820000


In [18]:
'''

Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

Use np.argmin().

'''

lowest_selling_store_index = np.argmin(total_sales_per_store)
lowest_selling_store_name = stores[lowest_selling_store_index]
lowest_selling_store_sales = total_sales_per_store[lowest_selling_store_index]
print(f"Store with lowest sales: {lowest_selling_store_name}")
print(f"Total sales for {lowest_selling_store_name}: {lowest_selling_store_sales}")

Store with lowest sales: Pune
Total sales for Pune: 1980000


In [19]:
'''

Question 18: Highest-Selling Category
Find the product category that generated the highest total sales across the company.

'''

highest_selling_category_index = np.argmax(total_sales_per_category)
highest_selling_category_name = categories[highest_selling_category_index]
print(f"Category with highest sales: {highest_selling_category_name}")

Category with highest sales: Electronics


In [20]:
'''

Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores.

'''

lowest_selling_category_index = np.argmin(total_sales_per_category)
lowest_selling_category_name = categories[lowest_selling_category_index]
print(f"Category with lowest sales: {lowest_selling_category_name}")

Category with lowest sales: Beauty


Part 5: Cost Analysis

In [21]:
'''

Question 20: Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories

'''

total_company_cost = np.sum(cost_data)
print("Total cost incurred by SmartMart across all stores and product categories:", total_company_cost)

Total cost incurred by SmartMart across all stores and product categories: 8600000


In [22]:
'''


Question 21: Store-Wise Cost
Calculate the total cost incurred by each store.

'''

total_cost_per_store = np.sum(cost_data, axis=1)
for store, total_cost in zip(stores, total_cost_per_store):
    print(f"Total cost for {store}: {total_cost}")

Total cost for Bengaluru: 1665000
Total cost for Hyderabad: 1685000
Total cost for Chennai: 1710000
Total cost for Mumbai: 2065000
Total cost for Pune: 1475000


In [23]:
'''

Question 22: Category-Wise Cost
Calculate the total cost incurred for each product category across all stores.

'''

total_cost_per_category = np.sum(cost_data, axis=0)
for category, total_cost in zip(categories, total_cost_per_category):
    print(f"Total cost for {category}: {total_cost}")

Total cost for Electronics: 3250000
Total cost for Groceries: 1660000
Total cost for Clothing: 1145000
Total cost for Furniture: 1045000
Total cost for Beauty: 665000
Total cost for Sports: 835000


In [24]:
'''

Question 23: Most Expensive Store
Identify the store with the highest total operating cost.

'''

highest_cost_store_index = np.argmax(total_cost_per_store)
highest_cost_store_name = stores[highest_cost_store_index]
print(f"Store with the highest total operating cost: {highest_cost_store_name}")

Store with the highest total operating cost: Mumbai


In [25]:
'''

Question 24: Lowest-Cost Store
Identify the store with the lowest total cost.

'''

lowest_cost_store_index = np.argmin(total_cost_per_store)
lowest_cost_store_name = stores[lowest_cost_store_index]
print(f"Store with the lowest total operating cost: {lowest_cost_store_name}")

Store with the lowest total operating cost: Pune


In [26]:
'''

Question 25: Most Expensive Product Category
Determine which product category has the highest total cost across all stores.

'''

most_expensive_category_index = np.argmax(total_cost_per_category)
most_expensive_category_name = categories[most_expensive_category_index]
print(f"Product category with the highest total cost: {most_expensive_category_name}")

Product category with the highest total cost: Electronics


Part 6: Profit Analysis Using Two Arrays

In [27]:
'''

Question 26: Profit Matrix
Calculate the profit generated for every store and product category.

Use:
profit_data = sales_data - cost_data

Display the complete profit matrix.

'''

profit_data = sales_data - cost_data
print("Profit matrix for every store and product category:")
print(profit_data)

Profit matrix for every store and product category:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [28]:
'''

Question 27: Store-Wise Profit
Calculate the total profit generated by each store.

'''

total_profit_per_store = np.sum(profit_data, axis=1)
for store, total_profit in zip(stores, total_profit_per_store):
    print(f"Total profit for {store}: {total_profit}")

Total profit for Bengaluru: 605000
Total profit for Hyderabad: 610000
Total profit for Chennai: 600000
Total profit for Mumbai: 755000
Total profit for Pune: 505000


In [29]:
'''

Question 28: Category-Wise Profit
Calculate the total profit generated by each product category.

'''

total_profit_per_category = np.sum(profit_data, axis=0)
for category, total_profit in zip(categories, total_profit_per_category):
    print(f"Total profit for {category}: {total_profit}")

Total profit for Electronics: 1040000
Total profit for Groceries: 525000
Total profit for Clothing: 455000
Total profit for Furniture: 370000
Total profit for Beauty: 345000
Total profit for Sports: 340000


In [30]:
'''

Question 29: Most Profitable Store
Identify the store that generated the highest total profit.

Display:

Store name
Total sales
Total cost
Total profit

'''

store_with_highest_profit_index = np.argmax(total_profit_per_store)
store_with_highest_profit_name = stores[store_with_highest_profit_index]
total_sales_highest_profit_store = total_sales_per_store[store_with_highest_profit_index]
total_cost_highest_profit_store = total_cost_per_store[store_with_highest_profit_index]
total_profit_highest_profit_store = total_profit_per_store[store_with_highest_profit_index]
print(f"Store with the highest total profit: {store_with_highest_profit_name}")
print(f"Total sales for {store_with_highest_profit_name}: {total_sales_highest_profit_store}")
print(f"Total cost for {store_with_highest_profit_name}: {total_cost_highest_profit_store}")
print(f"Total profit for {store_with_highest_profit_name}: {total_profit_highest_profit_store}")

Store with the highest total profit: Mumbai
Total sales for Mumbai: 2820000
Total cost for Mumbai: 2065000
Total profit for Mumbai: 755000


In [31]:
'''

Question 30: Least Profitable Store
Identify the store that generated the lowest total profit.

'''

least_profitable_store_index = np.argmin(total_profit_per_store)
least_profitable_store_name = stores[least_profitable_store_index]
print(f"Store with the lowest total profit: {least_profitable_store_name}")

Store with the lowest total profit: Pune


In [32]:
'''

Question 31: Most Profitable Category
Find the category with the highest total profit across all stores.

'''

most_profitable_category_index = np.argmax(total_profit_per_category)
most_profitable_category_name = categories[most_profitable_category_index]
print(f"Most profitable category: {most_profitable_category_name}")

Most profitable category: Electronics


In [33]:
'''

32: Least Profitable Category
Find the category with the lowest total profit.

'''

least_profitable_category_index = np.argmin(total_profit_per_category)
least_profitable_category_name = categories[least_profitable_category_index]
print(f"Least profitable category: {least_profitable_category_name}")

Least profitable category: Sports


In [34]:
'''

Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category

Use np.unravel_index().

'''

highest_profit_index = np.unravel_index(np.argmax(profit_data), profit_data.shape)
highest_profit_amount = profit_data[highest_profit_index]
print(f"Maximum individual profit: {highest_profit_amount}")

Maximum individual profit: 260000


In [35]:
'''

Question 34: Minimum Individual Profit
Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

'''

minimum_profit_index = np.unravel_index(np.argmin(profit_data), profit_data.shape)
minimum_profit_amount = profit_data[minimum_profit_index]
print(f"Minimum individual profit: {minimum_profit_amount}")

Minimum individual profit: 55000


Part 7: Profit Margin Analysis

In [36]:
'''

Question 35: Profit Margin Matrix
Calculate the profit margin percentage for every store-category combination.

Use:
profit_margin = (profit_data / sales_data) * 100

Round the result to two decimal places.

'''

profit_margin = (profit_data / sales_data) * 100
profit_margin_rounded = np.round(profit_margin, 2)
print("Profit Margin Matrix (rounded to 2 decimal places):")
print(profit_margin_rounded)

Profit Margin Matrix (rounded to 2 decimal places):
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [37]:
'''

Question 36: Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:

Store Profit Margin =
Total Store Profit / Total Store Sales × 100

'''

store_profit_margins = (np.sum(profit_data, axis=1) / np.sum(sales_data, axis=1)) * 100
print("Store-Wise Profit Margins:")
print(store_profit_margins)

Store-Wise Profit Margins:
[26.65198238 26.5795207  25.97402597 26.77304965 25.50505051]


In [38]:
'''

Question 37: Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.

'''

category_profit_margins = (np.sum(profit_data, axis=0) / np.sum(sales_data, axis=0)) * 100
print("Category-Wise Profit Margins:")
print(category_profit_margins)

Category-Wise Profit Margins:
[24.24242424 24.02745995 28.4375     26.14840989 34.15841584 28.93617021]


In [39]:
'''

Question 38: Best Store by Profit Margin
Identify the store with the highest overall profit margin.

'''

best_store_index = np.argmax(store_profit_margins)
best_store_name = stores[best_store_index]
print(f"Best Store by Profit Margin: {best_store_name}")

Best Store by Profit Margin: Mumbai


In [40]:
'''

Question 39: Best Category by Profit Margin
Identify the product category with the highest profit margin.

'''

best_category_index = np.argmax(category_profit_margins)
best_category_name = categories[best_category_index]
print(f"Best Category by Profit Margin: {best_category_name}")

Best Category by Profit Margin: Beauty


In [41]:
'''

Question 40: Low-Margin Transactions
Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing.

'''

low_margin_indices = np.where(profit_margin < 22)
print("Low-Margin Transactions (Profit Margin < 22%):")
for store_idx, category_idx in zip(*low_margin_indices):
    store_name = stores[store_idx]
    category_name = categories[category_idx]
    sales_value = sales_data[store_idx, category_idx]
    cost_value = cost_data[store_idx, category_idx]
    profit_value = profit_data[store_idx, category_idx]
    profit_margin_value = profit_margin_rounded[store_idx, category_idx]

    print(f"Store: {store_name}, Category: {category_name}, Sales: {sales_value}, Cost: {cost_value}, Profit: {profit_value}, Profit Margin: {profit_margin_value}%")



Low-Margin Transactions (Profit Margin < 22%):


Part 8: Boolean Filtering

In [42]:
'''

Question 41: High Sales Values
Find all sales values greater than ₹5,00,000.

'''

high_sales_indices = np.where(sales_data > 500000)
print("High Sales Values (Sales > ₹5,00,000):")
for store_idx, category_idx in zip(*high_sales_indices):
    store_name = stores[store_idx]
    category_name = categories[category_idx]
    sales_value = sales_data[store_idx, category_idx]
    cost_value = cost_data[store_idx, category_idx]
    profit_value = profit_data[store_idx, category_idx]
    profit_margin_value = profit_margin_rounded[store_idx, category_idx]

    print(f"Store: {store_name}, Category: {category_name}, Sales: {sales_value}, Cost: {cost_value}, Profit: {profit_value}, Profit Margin: {profit_margin_value}%")

High Sales Values (Sales > ₹5,00,000):
Store: Bengaluru, Category: Electronics, Sales: 850000, Cost: 640000, Profit: 210000, Profit Margin: 24.71%
Store: Hyderabad, Category: Electronics, Sales: 780000, Cost: 590000, Profit: 190000, Profit Margin: 24.36%
Store: Chennai, Category: Electronics, Sales: 920000, Cost: 700000, Profit: 220000, Profit Margin: 23.91%
Store: Mumbai, Category: Electronics, Sales: 1050000, Cost: 790000, Profit: 260000, Profit Margin: 24.76%
Store: Mumbai, Category: Groceries, Sales: 510000, Cost: 390000, Profit: 120000, Profit Margin: 23.53%
Store: Pune, Category: Electronics, Sales: 690000, Cost: 530000, Profit: 160000, Profit Margin: 23.19%


In [43]:
'''

Question 42: Low Sales Values
Find all sales values below ₹2,00,000.

'''

low_sales_indices = np.where(sales_data < 200000)
print("Low Sales Values (Sales < ₹2,00,000):")
for store_idx, category_idx in zip(*low_sales_indices):
    store_name = stores[store_idx]
    category_name = categories[category_idx]
    sales_value = sales_data[store_idx, category_idx]
    cost_value = cost_data[store_idx, category_idx]
    profit_value = profit_data[store_idx, category_idx]
    profit_margin_value = profit_margin_rounded[store_idx, category_idx]

    print(f"Store: {store_name}, Category: {category_name}, Sales: {sales_value}, Cost: {cost_value}, Profit: {profit_value}, Profit Margin: {profit_margin_value}%")

Low Sales Values (Sales < ₹2,00,000):
Store: Bengaluru, Category: Beauty, Sales: 190000, Cost: 125000, Profit: 65000, Profit Margin: 34.21%
Store: Chennai, Category: Beauty, Sales: 185000, Cost: 120000, Profit: 65000, Profit Margin: 35.14%
Store: Pune, Category: Beauty, Sales: 175000, Cost: 115000, Profit: 60000, Profit Margin: 34.29%


In [44]:
'''

Question 43: High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.

'''

high_profit_indices = np.where(profit_data > 150000)
print("High Profit Values (Profit > ₹1,50,000):")
for store_idx, category_idx in zip(*high_profit_indices):
    store_name = stores[store_idx]
    category_name = categories[category_idx]
    sales_value = sales_data[store_idx, category_idx]
    cost_value = cost_data[store_idx, category_idx]
    profit_value = profit_data[store_idx, category_idx]
    profit_margin_value = profit_margin_rounded[store_idx, category_idx]

    print(f"Store: {store_name}, Category: {category_name}, Sales: {sales_value}, Cost: {cost_value}, Profit: {profit_value}, Profit Margin: {profit_margin_value}%")

High Profit Values (Profit > ₹1,50,000):
Store: Bengaluru, Category: Electronics, Sales: 850000, Cost: 640000, Profit: 210000, Profit Margin: 24.71%
Store: Hyderabad, Category: Electronics, Sales: 780000, Cost: 590000, Profit: 190000, Profit Margin: 24.36%
Store: Chennai, Category: Electronics, Sales: 920000, Cost: 700000, Profit: 220000, Profit Margin: 23.91%
Store: Mumbai, Category: Electronics, Sales: 1050000, Cost: 790000, Profit: 260000, Profit Margin: 24.76%
Store: Pune, Category: Electronics, Sales: 690000, Cost: 530000, Profit: 160000, Profit Margin: 23.19%


In [45]:
'''

Question 44: Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

'''

moderate_sales_indices = np.where(np.logical_and(sales_data >= 250000, sales_data <= 500000))
print("Moderate Sales Values (₹2,50,000 <= Sales <= ₹5,00,000):")
for store_idx, category_idx in zip(*moderate_sales_indices):
    store_name = stores[store_idx]
    category_name = categories[category_idx]
    sales_value = sales_data[store_idx, category_idx]
    cost_value = cost_data[store_idx, category_idx]
    profit_value = profit_data[store_idx, category_idx]
    profit_margin_value = profit_margin_rounded[store_idx, category_idx]

    print(f"Store: {store_name}, Category: {category_name}, Sales: {sales_value}, Cost: {cost_value}, Profit: {profit_value}, Profit Margin: {profit_margin_value}%")

Moderate Sales Values (₹2,50,000 <= Sales <= ₹5,00,000):
Store: Bengaluru, Category: Groceries, Sales: 420000, Cost: 315000, Profit: 105000, Profit Margin: 25.0%
Store: Bengaluru, Category: Clothing, Sales: 310000, Cost: 220000, Profit: 90000, Profit Margin: 29.03%
Store: Bengaluru, Category: Furniture, Sales: 275000, Cost: 205000, Profit: 70000, Profit Margin: 25.45%
Store: Hyderabad, Category: Groceries, Sales: 460000, Cost: 350000, Profit: 110000, Profit Margin: 23.91%
Store: Hyderabad, Category: Clothing, Sales: 295000, Cost: 210000, Profit: 85000, Profit Margin: 28.81%
Store: Hyderabad, Category: Furniture, Sales: 310000, Cost: 225000, Profit: 85000, Profit Margin: 27.42%
Store: Chennai, Category: Groceries, Sales: 390000, Cost: 295000, Profit: 95000, Profit Margin: 24.36%
Store: Chennai, Category: Clothing, Sales: 340000, Cost: 245000, Profit: 95000, Profit Margin: 27.94%
Store: Chennai, Category: Furniture, Sales: 260000, Cost: 195000, Profit: 65000, Profit Margin: 25.0%
Store: 

In [46]:
'''

Question 45: Premium Performance
A store-category combination is considered premium when:

    Sales are greater than ₹5,00,000
    Profit is greater than ₹1,50,000
Find all premium-performing combinations.

'''

premium_indices = np.where(np.logical_and(sales_data > 500000, profit_data > 150000))
print("Premium-Performing Combinations (Sales > ₹5,00,000 and Profit > ₹1,50,000):")
for store_idx, category_idx in zip(*premium_indices):
    store_name = stores[store_idx]
    category_name = categories[category_idx]
    sales_value = sales_data[store_idx, category_idx]
    cost_value = cost_data[store_idx, category_idx]
    profit_value = profit_data[store_idx, category_idx]
    profit_margin_value = profit_margin_rounded[store_idx, category_idx]

    print(f"Store: {store_name}, Category: {category_name}, Sales: {sales_value}, Cost: {cost_value}, Profit: {profit_value}, Profit Margin: {profit_margin_value}%")

Premium-Performing Combinations (Sales > ₹5,00,000 and Profit > ₹1,50,000):
Store: Bengaluru, Category: Electronics, Sales: 850000, Cost: 640000, Profit: 210000, Profit Margin: 24.71%
Store: Hyderabad, Category: Electronics, Sales: 780000, Cost: 590000, Profit: 190000, Profit Margin: 24.36%
Store: Chennai, Category: Electronics, Sales: 920000, Cost: 700000, Profit: 220000, Profit Margin: 23.91%
Store: Mumbai, Category: Electronics, Sales: 1050000, Cost: 790000, Profit: 260000, Profit Margin: 24.76%
Store: Pune, Category: Electronics, Sales: 690000, Cost: 530000, Profit: 160000, Profit Margin: 23.19%


In [47]:
'''

Question 46: Underperforming Combinations
A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.

'''

underperforming_indices = np.where(np.logical_and(sales_data < 250000, profit_margin < 25))
print("Underperforming Combinations (Sales < ₹2,50,000 and Profit Margin < 25%):")
for store_idx, category_idx in zip(*underperforming_indices):
    store_name = stores[store_idx]
    category_name = categories[category_idx]
    sales_value = sales_data[store_idx, category_idx]
    cost_value = cost_data[store_idx, category_idx]
    profit_value = profit_data[store_idx, category_idx]
    profit_margin_value = profit_margin_rounded[store_idx, category_idx]

    print(f"Store: {store_name}, Category: {category_name}, Sales: {sales_value}, Cost: {cost_value}, Profit: {profit_value}, Profit Margin: {profit_margin_value}%")

Underperforming Combinations (Sales < ₹2,50,000 and Profit Margin < 25%):
Store: Pune, Category: Furniture, Sales: 225000, Cost: 170000, Profit: 55000, Profit Margin: 24.44%


In [48]:
'''

Question 47: Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().

'''

performance_classification = np.select(
    [sales_data >= 500000, (sales_data >= 250000) & (sales_data < 500000)],
    ["High", "Medium"],
    default="Low"
)
for store_idx in range(len(stores)):
    for category_idx in range(len(categories)):
        store_name = stores[store_idx]
        category_name = categories[category_idx]
        classification = performance_classification[store_idx, category_idx]
        print(f"Store: {store_name}, Category: {category_name}, Classification: {classification}")

Store: Bengaluru, Category: Electronics, Classification: High
Store: Bengaluru, Category: Groceries, Classification: Medium
Store: Bengaluru, Category: Clothing, Classification: Medium
Store: Bengaluru, Category: Furniture, Classification: Medium
Store: Bengaluru, Category: Beauty, Classification: Low
Store: Bengaluru, Category: Sports, Classification: Low
Store: Hyderabad, Category: Electronics, Classification: High
Store: Hyderabad, Category: Groceries, Classification: Medium
Store: Hyderabad, Category: Clothing, Classification: Medium
Store: Hyderabad, Category: Furniture, Classification: Medium
Store: Hyderabad, Category: Beauty, Classification: Low
Store: Hyderabad, Category: Sports, Classification: Low
Store: Chennai, Category: Electronics, Classification: High
Store: Chennai, Category: Groceries, Classification: Medium
Store: Chennai, Category: Clothing, Classification: Medium
Store: Chennai, Category: Furniture, Classification: Medium
Store: Chennai, Category: Beauty, Classific

Part 9: Target-Based Analysis

In [49]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [50]:
'''

Question 48: Target Comparison
Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

'''

target_comparison = sales_data >= sales_targets
for store_idx in range(len(stores)):
    for category_idx in range(len(categories)):
        store_name = stores[store_idx]
        category_name = categories[category_idx]
        meets_target = target_comparison[store_idx, category_idx]
        print(f"Store: {store_name}, Category: {category_name}, Meets Target: {meets_target}")

Store: Bengaluru, Category: Electronics, Meets Target: True
Store: Bengaluru, Category: Groceries, Meets Target: False
Store: Bengaluru, Category: Clothing, Meets Target: False
Store: Bengaluru, Category: Furniture, Meets Target: False
Store: Bengaluru, Category: Beauty, Meets Target: False
Store: Bengaluru, Category: Sports, Meets Target: False
Store: Hyderabad, Category: Electronics, Meets Target: False
Store: Hyderabad, Category: Groceries, Meets Target: True
Store: Hyderabad, Category: Clothing, Meets Target: False
Store: Hyderabad, Category: Furniture, Meets Target: True
Store: Hyderabad, Category: Beauty, Meets Target: True
Store: Hyderabad, Category: Sports, Meets Target: True
Store: Chennai, Category: Electronics, Meets Target: True
Store: Chennai, Category: Groceries, Meets Target: False
Store: Chennai, Category: Clothing, Meets Target: True
Store: Chennai, Category: Furniture, Meets Target: False
Store: Chennai, Category: Beauty, Meets Target: False
Store: Chennai, Category: 

In [51]:
'''

Question 49: Target Achievement Matrix
Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target

'''

target_achievement_matrix = sales_data >= sales_targets
print("Target Achievement Matrix (True = Achieved, False = Not Achieved):")
print(target_achievement_matrix)

Target Achievement Matrix (True = Achieved, False = Not Achieved):
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [52]:
'''

Question 50: Target Achievement Count
Calculate the number of categories in which each store achieved its target.

'''
achievement_counts = np.sum(target_achievement_matrix, axis=1)
print("Target Achievement Counts:")
for store_idx, count in enumerate(achievement_counts):
    print(f"Store: {stores[store_idx]}, Achieved Targets: {count}")

Target Achievement Counts:
Store: Bengaluru, Achieved Targets: 1
Store: Hyderabad, Achieved Targets: 4
Store: Chennai, Achieved Targets: 2
Store: Mumbai, Achieved Targets: 6
Store: Pune, Achieved Targets: 0


In [53]:
'''

Question 51: Best Target-Performing Store
Find the store that achieved the highest number of category targets.

'''

best_target_store_index = np.argmax(achievement_counts)
best_target_store_name = stores[best_target_store_index]
print(f"Best Target-Performing Store: {best_target_store_name}")

Best Target-Performing Store: Mumbai


In [54]:
'''

Question 52: Target Achievement by Category
Calculate how many stores achieved the target for each product category.

'''

target_achievement_by_category = np.sum(target_achievement_matrix, axis=0)
print("Target Achievement by Category:")
for category_idx, count in enumerate(target_achievement_by_category):
    print(f"Category: {categories[category_idx]}, Stores Achieved Target: {count}")

Target Achievement by Category:
Category: Electronics, Stores Achieved Target: 3
Category: Groceries, Stores Achieved Target: 2
Category: Clothing, Stores Achieved Target: 2
Category: Furniture, Stores Achieved Target: 2
Category: Beauty, Stores Achieved Target: 2
Category: Sports, Stores Achieved Target: 2


In [55]:
'''

Question 53: Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

'''

sales_target_variance = sales_data - sales_targets

print("Sales Target Variance (Actual - Target) for each store:")
for store_idx, store in enumerate(stores):
    print(f"{store}: {sales_target_variance[store_idx]}")

Sales Target Variance (Actual - Target) for each store:
Bengaluru: [ 50000 -30000 -10000 -25000 -10000  -5000]
Hyderabad: [-20000  10000 -25000  10000  10000  10000]
Chennai: [120000 -60000  20000 -40000 -15000 -15000]
Mumbai: [250000  60000  55000  45000  50000  60000]
Pune: [-110000  -45000  -40000  -75000  -25000  -25000]


In [56]:
'''

Question 54: Percentage Above or Below Target
Calculate the percentage variance from the target using:

Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100

'''

percentage_target = (sales_target_variance) / sales_targets * 100
print("The percentage variance from the target using:")
for store_idx, store in enumerate(stores):
    print(f"{store}: {percentage_target[store_idx]}")

The percentage variance from the target using:
Bengaluru: [ 6.25       -6.66666667 -3.125      -8.33333333 -5.         -2.17391304]
Hyderabad: [-2.5         2.22222222 -7.8125      3.33333333  5.          4.34782609]
Chennai: [ 15.         -13.33333333   6.25       -13.33333333  -7.5
  -6.52173913]
Mumbai: [31.25       13.33333333 17.1875     15.         25.         26.08695652]
Pune: [-13.75       -10.         -12.5        -25.         -12.5
 -10.86956522]


In [57]:
'''

Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.

'''

electronics_target = sales_targets[0]
failed_electronics_indices = np.where(sales_data[:, 0] < electronics_target)[0]

print("Stores that failed to achieve the Electronics target:")
for idx in failed_electronics_indices:
    print(f"{stores[idx]} - Sales: {sales_data[idx,0]}, Target: {electronics_target}")

Stores that failed to achieve the Electronics target:
Hyderabad - Sales: 780000, Target: 800000
Pune - Sales: 690000, Target: 800000


In [58]:
'''

Question 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all().

'''

store_achieving_target = np.all(target_achievement_matrix, axis=1)
print("Stores achieving all targets:", store_achieving_target)


Stores achieving all targets: [False False False  True False]


In [59]:
'''

Question 57: Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

Use np.any().

'''

store_achieving_atleast_target = np.any(target_achievement_matrix, axis=1)
print("Stores achieving at least one target:", store_achieving_atleast_target)


Stores achieving at least one target: [ True  True  True  True False]


Part 10: Discount Scenario

In [60]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [61]:
'''

Question 58: Discount Amount Matrix
Calculate the discount amount for each store-category combination.

Use broadcasting.

'''

discount_amount_matrix = np.multiply(sales_data,discount_rates)
print(discount_amount_matrix)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [62]:
'''

Question 59: Sales After Discount
Calculate the net sales value after applying the category-wise discounts.

'''

sales=sales_data-discount_amount_matrix
print(sales)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [63]:
'''

Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

'''

profit_dis_data=sales-cost_data
print(profit_dis_data)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [64]:
'''

Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.

'''

profit_dis_margin=(profit_dis_data/sales)
print(profit_dis_margin)

[[0.16339869 0.21052632 0.16508539 0.15289256 0.28489703 0.20987654]
 [0.15954416 0.19908467 0.16251246 0.17521994 0.27536232 0.21296296]
 [0.15458937 0.20377868 0.15224913 0.14772727 0.29494712 0.19896641]
 [0.16402116 0.19504644 0.16862745 0.17654809 0.2826087  0.21455939]
 [0.14653784 0.194282   0.13865546 0.14141414 0.28571429 0.21409214]]


In [65]:
'''

Question 62: Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

'''

print(np.sum(sales<cost_data))

0


In [66]:
'''

Question 63: Discount Impact
Calculate how much total revenue the company loses because of the proposed discounts.

'''

print(discount_amount_matrix.sum())

1146350.0


In [67]:
'''

Question 64: Store Most Affected by Discounts
Identify the store that loses the highest amount of revenue due to discounts.

'''

result=np.argmax(discount_amount_matrix.sum(axis=1))
print(stores[result])

Mumbai


Part 11: Tax and Price Adjustment

In [68]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [69]:
'''

Question 65: Tax Collection Matrix
Calculate the tax collected on sales for each store and category.

'''

tax=np.multiply(sales_data,tax_rates)
print(tax)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [70]:
'''

Question 66: Sales Including Tax
Calculate the final customer billing value after adding tax.

'''

tax_sales=np.add(sales_data,tax)
print(tax_sales)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [71]:
'''

Question 67: Store-Wise Tax Collection
Calculate the total tax collected by each store.

'''

store_tax=np.sum(tax,axis=1)
print(store_tax)

[321900. 321200. 331800. 401400. 274650.]


In [72]:
'''

Question 68: Category-Wise Tax Collection
Calculate total tax collected for each category.

'''

category_tax=np.sum(tax,axis=0)
print(category_tax)

[772200. 109250. 192000. 254700. 181800. 141000.]


In [73]:
'''

Question 68: Category-Wise Tax Collection
Calculate total tax collected for each category.

'''

category_tax=np.sum(tax,axis=0)
print(category_tax)

[772200. 109250. 192000. 254700. 181800. 141000.]


In [74]:
'''

Question 69: Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.

'''

highest_tax=np.argmax(store_tax)
print(stores[highest_tax])

Mumbai


Part 12: Array Modification

In [75]:
'''

Question 70: Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

'''

updated_pune_electronics_sales = sales_data.copy()
updated_pune_electronics_sales[1, 0] = 740000
print(updated_pune_electronics_sales)

[[ 850000  420000  310000  275000  190000  225000]
 [ 740000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [76]:
'''

Question 71: Revised Beauty Cost
Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

'''

revised_beauty_cost = cost_data * 0.92
print(revised_beauty_cost)

[[588800. 289800. 202400. 188600. 115000. 147200.]
 [542800. 322000. 193200. 207000. 128800. 156400.]
 [644000. 271400. 225400. 179400. 110400. 142600.]
 [726800. 358800. 243800. 230000. 151800. 188600.]
 [487600. 285200. 188600. 156400. 105800. 133400.]]


In [77]:
'''

Question 72: Furniture Cost Increase
Furniture costs increase by 12% for all stores.

Update only the Furniture column.

'''

revised_furniture_cost = cost_data * 1.12
print(revised_furniture_cost)

[[716800. 352800. 246400. 229600. 140000. 179200.]
 [660800. 392000. 235200. 252000. 156800. 190400.]
 [784000. 330400. 274400. 218400. 134400. 173600.]
 [884800. 436800. 296800. 280000. 184800. 229600.]
 [593600. 347200. 229600. 190400. 128800. 162400.]]


In [78]:
'''

Question 73: Store Closure Simulation
Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

'''

updated_sales_data = np.delete(sales_data, 1, axis=0)
updated_cost_data = np.delete(cost_data, 1, axis=0)
print(updated_sales_data)
print(updated_cost_data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
[[640000 315000 220000 205000 125000 160000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


In [79]:
'''

Question 74: Adding a New Store
A new Delhi store is opened with the following data:

'''

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

'''

Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

'''

updated_sales_data = np.vstack((sales_data, delhi_sales))
updated_cost_data = np.vstack((cost_data, delhi_cost))
updated_stores = np.append(stores, "Delhi")
print(updated_sales_data)
print(updated_cost_data)
print(updated_stores)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


In [80]:
'''

Question 75: Adding a New Product Category
SmartMart starts selling Home Appliances.

'''

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

'''

Add the new category as a column using np.column_stack() or np.hstack().

'''

updated_sales_data = np.column_stack((sales_data, home_appliance_sales))
updated_cost_data = np.column_stack((cost_data, home_appliance_cost))
updated_categories = np.append(categories, "Home Appliances")
print(updated_sales_data)
print(updated_cost_data)
print(updated_categories)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']


Part 13: Sorting and Ranking

In [81]:
'''

Question 76: Sort Stores by Sales
Sort stores in ascending order based on total sales.

Display store names and sales totals.

'''

sorted_sales_indices = np.argsort(np.sum(sales_data, axis=1))
for idx in sorted_sales_indices:
    print(f"{stores[idx]}: {np.sum(sales_data[idx])}")

Pune: 1980000
Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000


In [82]:
'''

Question 77: Rank Stores by Profit
Rank stores from highest to lowest total profit.

Use np.argsort().

'''

sorted_profit_indices = np.argsort(np.sum(profit_data, axis=1))
for idx in sorted_profit_indices:
    print(f"{stores[idx]}: {np.sum(profit_data[idx])}")

Pune: 505000
Chennai: 600000
Bengaluru: 605000
Hyderabad: 610000
Mumbai: 755000


In [83]:
'''

Question 78: Sort Categories by Revenue
Sort product categories from highest to lowest total revenue.

'''

sorted_revenue_indices = np.argsort(np.sum(sales_data, axis=0))
for idx in sorted_revenue_indices:
    print(f"{categories[idx]}: {np.sum(sales_data[:, idx])}")

Beauty: 1010000
Sports: 1175000
Furniture: 1415000
Clothing: 1600000
Groceries: 2185000
Electronics: 4290000


In [84]:
'''

Question 79: Top Three Store-Category Sales
Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value
Store name
Category name

'''

sorted_sales_indices = np.argsort(sales_data.flatten())[-3:]
for idx in sorted_sales_indices:
    store_idx = idx // sales_data.shape[1]
    category_idx = idx % sales_data.shape[1]
    print(f"Sales: {sales_data[store_idx, category_idx]}, Store: {stores[store_idx]}, Category: {categories[category_idx]}")

Sales: 850000, Store: Bengaluru, Category: Electronics
Sales: 920000, Store: Chennai, Category: Electronics
Sales: 1050000, Store: Mumbai, Category: Electronics


In [85]:
'''

Question 80: Bottom Three Profits
Find the three lowest profit values in the profit matrix.

'''

sorted_profit_indices = np.argsort(profit_data.flatten())[:3]
for idx in sorted_profit_indices:
    store_idx = idx // profit_data.shape[1]
    category_idx = idx % profit_data.shape[1]
    print(f"Profit: {profit_data[store_idx, category_idx]}, Store: {stores[store_idx]}, Category: {categories[category_idx]}")

Profit: 55000, Store: Pune, Category: Furniture
Profit: 60000, Store: Pune, Category: Sports
Profit: 60000, Store: Chennai, Category: Sports


Part 14: Statistical Analysis

In [86]:
'''

Question 81: Sales Statistics
Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile

'''

print("Minimum:", np.min(sales_data))
print("Maximum:", np.max(sales_data))
print("Mean:", np.mean(sales_data))
print("Median:", np.median(sales_data))
print("Standard deviation:", np.std(sales_data))
print("Variance:", np.var(sales_data))
print("25th percentile:", np.percentile(sales_data, 25))
print("50th percentile:", np.percentile(sales_data, 50))
print("75th percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard deviation: 230322.53954448793
Variance: 53048472222.222206
25th percentile: 228750.0
50th percentile: 302500.0
75th percentile: 416250.0


In [87]:
'''

Question 82: Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

'''

print(np.std(sales_data,axis=1))

[223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]


In [88]:
'''

Question 83: Category-Wise Standard Deviation
Determine which product category has the highest variation in sales across stores.

'''

category_std = np.std(sales_data, axis=0)
max_std_category_idx = np.argmax(category_std)
print(categories[max_std_category_idx])

Electronics


In [89]:
'''

Question 84: Sales Above Company Average
Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

'''

company_average = np.mean(sales_data)
above_average_count = np.sum(sales_data > company_average)
print(above_average_count)

10


In [90]:
'''

Question 85: Outlier Detection
Treat any sales value greater than:

Mean + 1.5 × Standard Deviation

as a high-value outlier.
Identify all such sales values.

'''

outliers = sales_data[sales_data > np.mean(sales_data) + 1.5 * np.std(sales_data)]
print(outliers)

[ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation

In [91]:
'''

Question 86: Flatten Sales Data
Convert the two-dimensional sales array into a one-dimensional array using:

flatten()
ravel()
Explain the difference between the two methods.

'''

flatten_sales = sales_data.flatten()
ravel_sales = sales_data.ravel()
print(flatten_sales)
print(ravel_sales)

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [92]:
'''

Question 87: Reshape Sales Data
Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.

'''

reshaped_3_10 = sales_data.reshape(3, 10)
reshaped_10_3 = sales_data.reshape(10, 3)
reshaped_2_15 = sales_data.reshape(2, 15)
reshaped_15_2 = sales_data.reshape(15, 2)
print(reshaped_3_10)
print(reshaped_10_3)
print(reshaped_2_15)
print(reshaped_15_2)

[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  510000]
 [ 375000  345000]
 [ 250000  29

In [93]:
'''

Question 88: Transpose Sales Data
Transpose the sales array so that:

Rows represent product categories
Columns represent stores
Display the new shape.

'''

transposed_sales = sales_data.T
print(transposed_sales)
print(transposed_sales.shape)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
(6, 5)


In [94]:
'''

Question 89: Combined Sales and Cost Array
Stack sales_data and cost_data vertically.

Display the resulting shape.

'''

combined_sales_cost = np.vstack((sales_data, cost_data))
print(combined_sales_cost)
print(combined_sales_cost.shape)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
(10, 6)


In [95]:
'''

Question 90: Store-Level Combined Data

Create a three-dimensional array where:

First layer contains sales data
Second layer contains cost data

Use np.stack().
Display the shape of the new array.

'''

store_level_data = np.stack((sales_data, cost_data))
print(store_level_data)
print(store_level_data.shape)

[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
(2, 5, 6)


Part 16: Missing Data Scenario

In [96]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [97]:
'''

Question 91: Missing Value Detection

Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values

'''

total_missing = np.isnan(sales_with_missing).sum()
missing_indices = np.where(np.isnan(sales_with_missing))
missing_stores = np.unique(missing_indices[0])
missing_categories = np.unique(missing_indices[1])
print(total_missing)
print(missing_indices)
print(missing_stores)
print(missing_categories)

4
(array([0, 1, 3, 4]), array([2, 3, 1, 4]))
[0 1 3 4]
[1 2 3 4]


In [98]:
'''

Question 92: Replace Missing Values with Zero
Replace all missing sales values with zero.

'''

sales_with_zeros = np.nan_to_num(sales_with_missing, nan=0)
print(sales_with_zeros)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [99]:
'''

Question 93: Replace with Company Average
Replace missing values with the overall average of available sales values.

Use np.nanmean().

'''

company_average = np.nanmean(sales_with_missing)
sales_with_average = np.where(np.isnan(sales_with_missing), company_average, sales_with_missing)
print(sales_with_average)

[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


In [100]:
'''

Question 94: Replace with Category Average
Replace each missing value with the average sales value of its respective product category.

'''

category_averages = np.nanmean(sales_with_missing, axis=0)
sales_with_category_averages = np.where(np.isnan(sales_with_missing), category_averages, sales_with_missing)
print(sales_with_category_averages)

[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


In [101]:
'''

Question 95: Missing Value Impact
Compare total sales before and after replacing missing values with zero.

'''

total_sales_before = np.nansum(sales_with_missing)
total_sales_after = np.nansum(sales_with_zeros)
print(total_sales_before)
print(total_sales_after)

10370000.0
10370000.0


Part 17: Conditional Business Decisions

In [105]:
'''

Question 96: Store Performance Labels
Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select().

'''

store_totals = np.sum(sales_data, axis=1)

conditions = [
    store_totals > 2800000,
    (store_totals >= 2400000) & (store_totals <= 2800000)
]
choices = ["Excellent", "Good"]

store_performance = np.select(conditions, choices, default="Needs Improvement")

for name, total, label in zip(stores, store_totals, store_performance):
    print(f"Store: {name:<10} | Total Sales: ₹{total:,.0f} | Status: {label}")

Store: Bengaluru  | Total Sales: ₹2,270,000 | Status: Needs Improvement
Store: Hyderabad  | Total Sales: ₹2,295,000 | Status: Needs Improvement
Store: Chennai    | Total Sales: ₹2,310,000 | Status: Needs Improvement
Store: Mumbai     | Total Sales: ₹2,820,000 | Status: Excellent
Store: Pune       | Total Sales: ₹1,980,000 | Status: Needs Improvement


In [106]:
'''

Question 97: Profitability Classification
Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero

'''

conditions=[
    sales_data > 200000,
    sales_data >=100000,
    sales_data < 100000
]
choices=[
    "Highly Profitable",
    "Profitable",
    "Low Profit"
]
result=np.select(conditions,choices,default="Loss")
print(result)

[['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Highly Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Highly Profitable' 'Highly Profitable']
 ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
  'Highly Profitable' 'Profitable' 'Highly Profitable']]


In [110]:
'''

Question 98: Expansion Recommendation
A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%

Identify eligible stores.

'''

profit=profit_data.sum(axis=1)
profit_m1=profit_margin.sum(axis=1)
result=np.logical_and(sales_value > 2500000,profit > 700000,profit_m1 > 25)
print(result)

[False False False False False]


In [111]:
'''

Question 99: Category Promotion Recommendation
A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%

Identify the categories that satisfy these conditions.

'''

sales_category=np.mean(sales_data,axis=0)
profit_category=profit_margin.sum(axis=0)
result=np.logical_and(sales_category>300000,profit_category)
print(result)

[ True  True  True False False False]


In [112]:
'''

Question 100: Cost Optimization Recommendation
Find store-category combinations where:

Cost is greater than ₹2,50,000
Profit margin is below 25%

These combinations should be reviewed for cost optimization.

'''

cost_category=cost_data.sum(axis=0)
profit_category=profit_margin.sum(axis=0)
result=np.logical_and(cost_category>250000,profit_category)
print(result)

[ True  True  True  True  True  True]


Part 18: Inventory Scenario

In [113]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

In [114]:
'''

Question 101: Closing Stock
Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

'''

closing_stock = opening_stock - units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [115]:
'''

Question 102: Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units.

'''

low_stock = closing_stock < 30
print(low_stock)

[[ True False False  True False False]
 [ True False False  True False False]
 [ True False False  True False False]
 [ True False False False False False]
 [ True False False  True False False]]


In [116]:
'''

Question 103: Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.

'''

unsold_percentage = (np.sum(units_sold) / np.sum(opening_stock)) * 100
print(unsold_percentage)

80.33707865168539


In [117]:
'''

Question 104: Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

'''

total_sold = np.sum(units_sold, axis=0)
total_opening = np.sum(opening_stock, axis=0)
fast_moving = (total_sold / total_opening) > 0.8
print(fast_moving)

[False  True  True False False False]


In [119]:
'''

Question 105: Category-Wise Units Sold
Calculate the total units sold for each product category.

'''

category_units_sold = np.sum(units_sold, axis=0)
print(category_units_sold)

[ 485 1950 1240  345  980  720]


In [120]:
'''

Question 106: Store-Wise Units Sold
Calculate total units sold by each store.

'''

store_units_sold = np.sum(units_sold, axis=1)
print(store_units_sold)

[1110 1175 1095 1390  950]


In [121]:
'''

Question 107: Best Store by Unit Sales
Identify the store that sold the highest total number of units.

'''

best_store_index = np.argmax(store_units_sold)
best_store = stores[best_store_index]
print(best_store)

Mumbai


In [122]:
'''

Question 108: Reorder Requirement
A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

'''

reorder_required = closing_stock < 25
print(reorder_required)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [123]:
'''

Question 109: Reorder Quantity
Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

'''

reorder_quantity = np.where(closing_stock < 25, 100 - closing_stock, 0)
print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions

In [124]:
'''

Question 110: Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().

'''

cumulative_sales = np.cumsum(sales_data, axis=1)
print(cumulative_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [125]:
'''

Question 111: Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.

'''

flattened_sales = sales_data.flatten()
cumulative_company_sales = np.cumsum(flattened_sales)
print(cumulative_company_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [126]:
'''

Question 112: Sales Difference Between Categories
Calculate the difference between consecutive category sales for each store using np.diff().

'''

sales_differences = np.diff(sales_data, axis=1)
print(sales_differences)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [127]:
'''

Question 113: Unique Sales Values
Find all unique sales values in sales_data.

Also count the frequency of each value.

'''

unique_sales, counts = np.unique(sales_data, return_counts=True)
print(unique_sales)
print(counts)

[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
[1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [128]:
'''

Question 114: Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

'''

sales_value = 420000
location = np.where(sales_data == sales_value)
print(location)

(array([0]), array([1]))


In [129]:
'''

Question 115: Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

'''

is_profitable = sales_data > cost_data
all_profitable = np.all(is_profitable)
print(is_profitable)
print(all_profitable)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
True


In [130]:
'''

Question 116: Clip Profit Values
For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.

'''

min_profit = 75000
max_profit = 250000
reporting_profit = np.clip(profit_data, min_profit, max_profit)
print(reporting_profit)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [131]:
'''

Question 117: Normalize Sales Data
Normalize all sales values using min-max normalization:

Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

'''

min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)
print(normalized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


In [132]:
'''

Question 118: Standardize Sales Data
Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

'''

mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
standardized_sales = (sales_data - mean_sales) / std_sales
print(standardized_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [133]:
'''

Question 119: Round Values
Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values

'''

rounded_profit_margin = np.round(profit_margin, decimals=2)
nearest_profit_margin = np.round(profit_margin)
floor_profit_margin = np.floor(profit_margin)
ceiling_profit_margin = np.ceil(profit_margin)
print(rounded_profit_margin)
print(nearest_profit_margin)
print(floor_profit_margin)
print(ceiling_profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


In [137]:
'''

Question 120: Save and Load Data
Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy

Load them back and verify that the loaded arrays are equal to the original arrays.

'''

np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)
loaded_sales_data = np.load("sales_data.npy")
loaded_cost_data = np.load("cost_data.npy")
loaded_profit_data = np.load("profit_data.npy")
print(np.array_equal(sales_data, loaded_sales_data))
print(np.array_equal(cost_data, loaded_cost_data))
print(np.array_equal(profit_data, loaded_profit_data))

True
True
True


Part 20: Final Retail Analytics Project

In [139]:

# --- 1. COMPANY SUMMARY CALCULATIONS ---
total_company_sales = np.sum(sales_data)
total_company_cost = np.sum(cost_data)
total_company_profit = np.sum(profit_data)
overall_margin = (total_company_profit / total_company_sales) * 100
avg_transaction = np.mean(sales_data)
highest_sale = np.max(sales_data)
lowest_sale = np.min(sales_data)

# --- 2. STORE PERFORMANCE ---
total_sales_store = np.sum(sales_data, axis=1)
total_cost_store = np.sum(cost_data, axis=1)
total_profit_store = np.sum(profit_data, axis=1)
store_margin = (total_profit_store / total_sales_store) * 100
targets_achieved = np.sum(sales_data >= sales_targets, axis=1)
store_units = np.sum(units_sold, axis=1)

# Expansion Eligibility
eligible_mask = (total_sales_store > 2500000) & (total_profit_store > 700000) & (store_margin > 25)
eligible_stores = stores[eligible_mask]

# --- 3. CATEGORY PERFORMANCE ---
total_sales_cat = np.sum(sales_data, axis=0)
total_cost_cat = np.sum(cost_data, axis=0)
total_profit_cat = np.sum(profit_data, axis=0)
cat_margin = (total_profit_cat / total_sales_cat) * 100
cat_avg_sales = np.mean(sales_data, axis=0)
cat_targets_stores = np.sum(sales_data >= sales_targets, axis=0)
cat_units = np.sum(units_sold, axis=0)

# --- 4. RECOMMENDATIONS DATA ---
best_store_idx = np.argmax(total_profit_store)
worst_store_idx = np.argmin(total_profit_store)
most_prof_cat_idx = np.argmax(total_profit_cat)

# Cost Optimization: Cost > 250,000 and Margin < 25%
cost_opt_mask = (cost_data > 250000) & (profit_margin < 25)
cost_opt_indices = np.argwhere(cost_opt_mask)

# Inventory Reorder: Closing Stock < 25
reorder_mask = closing_stock < 25
reorder_indices = np.argwhere(reorder_mask)

# --- 5. FORMATTED REPORT ---
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("===================================")
print("\nCOMPANY SUMMARY")
print("---------------")
print(f"Total Sales: ₹{total_company_sales:,.2f}")
print(f"Total Cost: ₹{total_company_cost:,.2f}")
print(f"Total Profit: ₹{total_company_profit:,.2f}")
print(f"Overall Profit Margin: {overall_margin:.2f}%")

print("\nBEST-PERFORMING STORE")
print("---------------------")
print(f"Store: {stores[best_store_idx]}")
print(f"Sales: ₹{total_sales_store[best_store_idx]:,.2f}")
print(f"Cost: ₹{total_cost_store[best_store_idx]:,.2f}")
print(f"Profit: ₹{total_profit_store[best_store_idx]:,.2f}")
print(f"Profit Margin: {store_margin[best_store_idx]:.2f}%")

print("\nMOST PROFITABLE CATEGORY")
print("------------------------")
print(f"Category: {categories[most_prof_cat_idx]}")
print(f"Sales: ₹{total_sales_cat[most_prof_cat_idx]:,.2f}")
print(f"Cost: ₹{total_cost_cat[most_prof_cat_idx]:,.2f}")
print(f"Profit: ₹{total_profit_cat[most_prof_cat_idx]:,.2f}")
print(f"Profit Margin: {cat_margin[most_prof_cat_idx]:.2f}%")

print("\nEXPANSION RECOMMENDATIONS")
print("-------------------------")
print(f"Eligible Stores: {', '.join(eligible_stores) if len(eligible_stores) > 0 else 'None'}")

print("\nCOST OPTIMIZATION")
print("-----------------")
for r, c in cost_opt_indices:
    print(f"Store: {stores[r]}, Category: {categories[c]}, Cost: ₹{cost_data[r,c]:,.2f}, Margin: {profit_margin[r,c]:.2f}%")

print("\nINVENTORY REORDER")
print("-----------------")
for r, c in reorder_indices:
    print(f"Store: {stores[r]}, Category: {categories[c]}, Closing Stock: {closing_stock[r,c]}, Reorder Qty: {reorder_quantity[r,c]}")

SMARTMART RETAIL PERFORMANCE REPORT

COMPANY SUMMARY
---------------
Total Sales: ₹11,675,000.00
Total Cost: ₹8,600,000.00
Total Profit: ₹3,075,000.00
Overall Profit Margin: 26.34%

BEST-PERFORMING STORE
---------------------
Store: Mumbai
Sales: ₹2,820,000.00
Cost: ₹2,065,000.00
Profit: ₹755,000.00
Profit Margin: 26.77%

MOST PROFITABLE CATEGORY
------------------------
Category: Electronics
Sales: ₹4,290,000.00
Cost: ₹3,250,000.00
Profit: ₹1,040,000.00
Profit Margin: 24.24%

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores: Mumbai

COST OPTIMIZATION
-----------------
Store: Bengaluru, Category: Electronics, Cost: ₹640,000.00, Margin: 24.71%
Store: Hyderabad, Category: Electronics, Cost: ₹590,000.00, Margin: 24.36%
Store: Hyderabad, Category: Groceries, Cost: ₹350,000.00, Margin: 23.91%
Store: Chennai, Category: Electronics, Cost: ₹700,000.00, Margin: 23.91%
Store: Chennai, Category: Groceries, Cost: ₹295,000.00, Margin: 24.36%
Store: Mumbai, Category: Electronics, 